spring:
  application:
    name: UsersService
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/usersdb
  #url: jdbc:postgresql://quirky_brahmagupta:5432/eldelivery
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true